app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name="index"),
    path('members/', include('members.urls')),
    path('refrigerator/', include('recipes.urls')),
]

# /media/로 접근시 폴더로 이동하게 설정
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

app/members/urls.py
from django.urls import path

from members.views import login_view, signup_view, logout_view

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('signup/', signup_view, name="signup"),
    path('logout/', logout_view, name="logout"),
]

app/recipes/urls.py
from django.urls import path

from recipes.views import refrigerator_view, add_view, add_ingredient_view, modify_ingredient_view, \
    delete_ingredient_view, recipe_view

app_name = 'recipes'

urlpatterns = [
    path('', refrigerator_view, name="refrigerator"),
    path('add/', add_view, name="add"),
    path('add_ingredient/', add_ingredient_view, name="add_ingredient"),
    path('modify/<int:ingredient>', modify_ingredient_view, name="modify_ingredient"),
    path('delete/<int:ingredient>', delete_ingredient_view, name="delete_ingredient"),
    path('recipe/', recipe_view, name="recipe"),
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
from recipes.models import Refrigerator


class User(AbstractUser):
    name = models.CharField(max_length=30)
    refrigerator = models.OneToOneField(Refrigerator, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.refrigerator = Refrigerator.objects.create()
        super().save(*args, **kwargs)

app/recipes/models.py
import datetime

from django.db import models

from config.settings import AUTH_USER_MODEL

User = AUTH_USER_MODEL


# Create your models here.
class Ingredient(models.Model):
    STATE_CHOICES = (
        ('freeze', 'freeze'),
        ('cold', 'cold'),
    )

    name = models.CharField(max_length=30)
    state = models.CharField(max_length=20, choices=STATE_CHOICES)
    shelf_life = models.IntegerField()  # 유통기한


class Refrigerator(models.Model):
    ingredients = models.ManyToManyField(Ingredient, through='MyIngredientInfo')


# 중간모델 사용해서 구매일, 양 저장
class MyIngredientInfo(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    refrigerator = models.ForeignKey(Refrigerator, on_delete=models.CASCADE)
    buy_date = models.DateField(default=datetime.date.today)
    quantity = models.CharField(max_length=30)

    def left_days(self):
        shelf_life = self.ingredient.shelf_life
        keeping_date = self.buy_date + datetime.timedelta(days=shelf_life)
        left = keeping_date - datetime.datetime.today().date()
        left_days = left.days

        return left_days

app/config/views.py
from django.shortcuts import render


def index_view(request):
    return render(request, 'index.html')

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

# Create your views here.
from members.models import User


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        login(request, user)
        return redirect('index')
    else:
        return render(request, 'members/login.html')


def signup_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        name = request.POST['name']
        user = User.objects.create_user(username=username, password=password, name=name)
        login(request, user)
        return redirect('index')

    return render(request, 'members/signup.html')


def logout_view(request):
    logout(request)
    return redirect('index')

app/recipes/views.py
import requests
from bs4 import BeautifulSoup
from django.shortcuts import render, redirect

# Create your views here.
from members.models import User
from recipes.models import Ingredient, MyIngredientInfo


def refrigerator_view(request):
    user = User.objects.get(username=request.user.username)
    freeze = MyIngredientInfo.objects.filter(refrigerator=user.refrigerator, ingredient__state="freeze")
    freeze = sorted(freeze, key=lambda x: x.left_days())
    cold = MyIngredientInfo.objects.filter(refrigerator=user.refrigerator, ingredient__state="cold")
    cold = sorted(cold, key=lambda x: x.left_days())

    data = {
        "freeze": freeze,
        "cold": cold
    }

    return render(request, 'refrigerator/main.html', data)


def add_view(request):
    if request.method == 'POST':
        user = User.objects.get(username=request.user.username)
        ingredient = Ingredient.objects.get(name=request.POST['ingredient'], state=request.POST['state'])
        quantity = request.POST['quantity']
        date = request.POST['date']

        MyIngredientInfo.objects.create(ingredient=ingredient, refrigerator=user.refrigerator, quantity=quantity,
                                        buy_date=date)

        return redirect('recipes:refrigerator')
    else:
        state = request.GET['state']
        data = {
            "state": request.GET['state'],
            "ingredients": Ingredient.objects.filter(state=state).order_by('name'),
        }
        return render(request, 'refrigerator/add.html', data)


def add_ingredient_view(request):
    if request.method == 'POST':
        name = request.POST['name']
        shelf_life = request.POST['shelf_life']
        state = request.POST['state']
        Ingredient.objects.create(name=name, shelf_life=shelf_life, state=state)

        response = redirect('recipes:add')
        response['Location'] += f'?state={state}'
        return response
    else:
        data = {
            "state": request.GET['state']
        }
        return render(request, 'refrigerator/add_ingredient.html', data)


def modify_ingredient_view(request, ingredient):
    my_ingredient = MyIngredientInfo.objects.get(pk=ingredient)
    if request.method == 'POST':
        my_ingredient.quantity = request.POST["quantity"]
        my_ingredient.save()
        return redirect('recipes:refrigerator')
    else:
        data = {
            "ingredient": my_ingredient,
        }
        return render(request, 'refrigerator/modify.html', data)


def delete_ingredient_view(request, ingredient):
    MyIngredientInfo.objects.get(pk=ingredient).delete()
    return redirect('recipes:refrigerator')


def recipe_view(request):
    # 크롤링
    base_url = 'https://www.10000recipe.com/recipe/list.html?q='

    selected = request.GET.getlist('ingredient', None)

    # 자동추천
    if len(selected) == 0:
        user = User.objects.get(username=request.user.username)
        ingredients = MyIngredientInfo.objects.filter(refrigerator=user.refrigerator)
        ingredients = sorted(ingredients, key=lambda x: x.left_days())

        selected = [ingredients[0].ingredient.name, ingredients[1].ingredient.name]

    query = "%2B".join(selected)
    search_url = base_url + query

    response = requests.get(search_url)
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    items = soup.select('.rcp_m_list2 .common_sp_list_li')

    if len(items) == 0:
        data = {
            "items": None,
        }
    else:
        recipe_list = []
        for item in items:
            temp_dict = {}
            temp_dict["title"] = item.select_one('.common_sp_caption_tit').get_text()
            temp_dict["link"] = 'https://www.10000recipe.com/' + item.select_one('a.common_sp_link')['href']
            temp_dict["img"] = item.select_one('.common_sp_link > img')['src']
            recipe_list.append(temp_dict)

        data = {
            "ingredient": "+".join(selected),
            "items": recipe_list,
        }

    print(data)
    return render(request, 'refrigerator/recipe.html', data)

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Recipe</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<header>
    <nav class="nav">
        <a class="nav_title" href="{% url 'index' %}">RECIPE</a>
        <div class="nav_bar">
            {% if request.user.is_authenticated %}
            <a class="nav_item" href="{% url 'recipes:refrigerator' %}">내 냉장고</a>
            <a class="nav_item" href="{% url 'members:logout' %}">로그아웃</a>
            {% else %}
            <a class="nav_item" href="{% url 'members:signup' %}">회원가입</a>
            <a class="nav_item" href="{% url 'members:login' %}">로그인</a>
            {% endif %}
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
<div>
    <footer class="footer">
        <p>&copy; Copyright 2021 by Hyeonggeun Oh</p>
    </footer>
</div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if request.user.is_authenticated %}
<div id="first_text"><span>{{ request.user.name }}</span>님 만나서 반가워요.</div>
{% else %}
<div>&nbsp;</div>
{% endif %}
<div id="index">
    <h2 class="sub_title">냉장고 속 음식을 관리하고</h2>
    <h2 class="sub_title">레시피를 추천받아보세요.</h2>
</div>

{% endblock %}

app/templates/members/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="sub_title">로그인</h2>
<div class="container">
    <div class="login_box">
        <form method="POST" action="{% url 'members:login' %}">
            {% csrf_token %}
            <div>
                <input type="text" name="username" placeholder="아이디"/>
                <input type="password" name="password" placeholder="비밀번호"/>
            </div>
            <button class="btn">로그인</button>
        </form>
    </div>
    <div class="login_signup">
        <p>회원가입을 하시면 다양하고 특별한<br/>혜택이 준비되어 있습니다.</p>
        <a href="{% url 'members:signup' %}">회원가입</a>
    </div>
</div>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <h2 class="sub_title">회원가입</h2>
      <div class="container">
        <form method="POST" action="{% url 'members:signup' %}">
          {% csrf_token %}
          <table>
            <tr>
              <th>아이디</th>
              <td><input type="text" name="username"/></td>
            </tr>
            <tr>
              <th>비밀번호</th>
              <td><input type="password" name="password"/></td>
            </tr>
            <tr>
              <th>이름</th>
              <td><input type="text" name="name"/></td>
            </tr>
          </table>
          <button class="btn">가입하기</button>
        </form>
      </div>
{% endblock %}

app/templates/refrigerator/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if state == 'freeze' %}
<h2 class="sub_title">냉동실에 식재료 추가</h2>
{% else %}
<h2 class="sub_title">냉장실에 식재료 추가</h2>
{% endif %}

<div class="container">
    <form method="POST" action="{% url 'recipes:add' %}">
        {% csrf_token %}
        <input type="hidden" name="state" value="{{ state }}">
        <table>
            <tr>
                <th>식재료</th>
                <td>
                    <select name="ingredient">
                        <option value="">식재료 선택</option>
                        {% for ingredient in ingredients %}
                        <option value="{{ ingredient.name }}">{{ ingredient.name }}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th></th>
                <td id="sup_text">없는 재료는 직접 추가할 수 있어요!</td>
            </tr>
            <tr>
                <th>구매일</th>
                <td><input type="date" name="date"/></td>
            </tr>
            <tr>
                <th>양</th>
                <td><input type="text" name="quantity" placeholder="(개수, g 등)"/></td>
            </tr>
        </table>
        <button class="btn">추가하기</button>
    </form>
    <a id="add_ingredient" href="{% url 'recipes:add_ingredient' %}?state={{ state }}">추가하기</a>
</div>
{% endblock %}

app/templates/refrigerator/add_ingredient.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h2 class="sub_title">식재료 추가</h2>

<div class="container">
    <form method="POST" action="{% url 'recipes:add_ingredient' %}">
        {% csrf_token %}
        <input type="hidden" name="state" value="{{ state }}">
        <table id="ingredient_table">
            <tr>
                <th>식재료명</th>
                <td>
                    <input type="text" name="name"/>
                </td>
            </tr>
            <tr>
                <th>유통기한(일)</th>
                <td>
                    <input type="text" name="shelf_life" placeholder=" 숫자만 입력"/>
                </td>
            </tr>
        </table>
        <button class="btn">추가하기</button>
    </form>
</div>
{% endblock %}

app/templates/refrigerator/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form id="refrigerator_container" action="{% url 'recipes:recipe' %}">
    <div id="pos_container">
        <div class="refrigerator" id="freeze">
            <p class="refrigerator_title">냉동실</p>
            {% for item in freeze %}
            <a href="{% url 'recipes:modify_ingredient' ingredient=item.pk %}">
                <div class="refrigerator_item">
                    <input type="checkbox" class="ingredient_check_box" name="ingredient" value="{{ item.ingredient.name }}">{{ item.ingredient.name }}
                    <span>- 남은 유통기한: </span>
                    <span class="left_days">{{ item.left_days }}일</span>
                    <span> ({{ item.quantity }})</span>
                    <a class="del_btn" href="{% url 'recipes:delete_ingredient' ingredient=item.pk %}">x</a>
                </div>
            </a>
            {% endfor %}
        </div>
        <div class="refrigerator" id="cold">
            <p class="refrigerator_title">냉장고</p>
            {% for item in cold %}
            <a href="{% url 'recipes:modify_ingredient' ingredient=item.pk %}">
                <div class="refrigerator_item">
                    <input type="checkbox" class="ingredient_check_box" name="ingredient" value="{{ item.ingredient.name }}">{{ item.ingredient.name }}
                    <span>- 남은 유통기한: </span>
                    <span class="left_days">{{ item.left_days }}일</span>
                    <span> ({{ item.quantity }})</span>
                    <a class="del_btn" href="{% url 'recipes:delete_ingredient' ingredient=item.pk %}">x</a>
                </div>
            </a>
            {% endfor %}
        </div>
        <button id="go_recipe">선택한 재료와 맞는 레시피 보러가기</button>
        <p style="text-align: center">(아무것도 선택하지 않으면 유통기한이 임박한 재료로 추천해드려요!)</p>
    </div>
    <a class="add_btn" id="freeze_btn" href="{% url 'recipes:add' %}?state=freeze">+</a>
    <a class="add_btn" id="cold_btn" href="{% url 'recipes:add' %}?state=cold">+</a>
</form>

{% endblock %}

app/templates/refrigerator/modify.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="sub_title">{{ingredient.ingredient.name}}</h2>

<div class="container">
    <form method="POST" action="{% url 'recipes:modify_ingredient' ingredient=ingredient.pk %}">
        {% csrf_token %}
        <input type="hidden" name="state" value="{{ state }}">
        <table>
            <tr>
                <th>식재료</th>
                <td>
                    {{ingredient.ingredient.name}}
                </td>
            </tr>
            <tr>
                <th>구매일</th>
                <td>{{ingredient.buy_date}}</td>
            </tr>
            <tr>
                <th>양(g)</th>
                <td><input type="text" name="quantity" placeholder="(개수, g 등)" value="{{ ingredient.quantity }}"/></td>
            </tr>
        </table>
        <button class="btn">수정하기</button>
    </form>
</div>
{% endblock %}

app/templates/refrigerator/recipe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="sub_title">{{ ingredient }} 레시피</h2>
<div id="recipe_container">
    {% if items == None %}
    <p>적절한 레시피가 존재하지 않습니다.</p>
    <p>다른 재료를 골라서 다시 시도해보세요.</p>
    {% else %}
    {% for item in items %}
    <div class="recipe_card">
        <a href="{{ item.link }}">
            <img src="{{ item.img }}">
            <p>{{ item.title }}</p>
        </a>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}